<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros" />
  <PropertyGroup>
    <!-- Builds are side-effect free unless deployment is explicitly enabled. -->
    <SkseDeployOnBuild Condition="'$(SkseDeployOnBuild)' == ''">false</SkseDeployOnBuild>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <PostBuildEvent Condition="'$(SkseDeployOnBuild)' == 'true' and '$(Skyrim64Path)' != ''">
      <Command>copy "$(TargetPath)" "$(Skyrim64Path)\$(TargetFileName)" /Y</Command>
      <Message>Installing DLL...</Message>
    </PostBuildEvent>
  </ItemDefinitionGroup>
  <ItemGroup />
</Project>
